
parameters:
    locale: 'en'
    app.uploads_dir: '%kernel.project_dir%/public/uploads/'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Service\FileSystem\FileManager:
        arguments:
        - '@app.filesystem.file_name'
        - '%app.uploads_dir%'

    app.filesystem.file_name:
        class: App\Service\Filesystem\Md5FileName

    App\Service\FileSystem\Md5FileName: '@app.filesystem.file_name'


